#!/bin/bash

# modify from https://stackoverflow.com/a/12179492
diff-lines() {
  local path=
  local line=
  while read; do
    esc=$'\033'
    if [[ $REPLY =~ ---\ (a/)?.* ]]; then
      continue
    elif [[ $REPLY =~ \+\+\+\ (b/)?([^[:blank:]$esc]+).* ]]; then
      path=${BASH_REMATCH[2]}
    elif [[ $REPLY =~ @@\ -[0-9]+(,[0-9]+)?\ \+([0-9]+)(,[0-9]+)?\ @@.* ]]; then
      line=${BASH_REMATCH[2]}
    elif [[ $REPLY =~ ^($esc\[[0-9;]+m)*([\ +-]) ]]; then
      if [[ $path == *"${EXT}" && $REPLY == "+"* ]]; then  # we only care about added lines
        echo "$path:$line:"
      fi
      if [[ ${BASH_REMATCH[2]} != - ]]; then
        ((line++))
      fi
    fi
  done
}

LINT="pycodestyle"
BRANCH="stage"
EXT="\.py$"

while getopts ":x:b:e:l:h" opt; do
  case $opt in
    x)
      LINT=$OPTARG
      ;;
    b)
      BRANCH=$OPTARG
      ;;
    e)
      EXT=$OPTARG
      ;;
    l)
      LINES=$OPTARG
      ;;
    h)
      echo -e "Usage: git-diff-lint [options]\n"
      echo "Options:"
      echo -e "  -x\t lint command (default: pycodestyle)"
      echo -e "  -b\t parent branch (default: stage)"
      echo -e "  -e\t file extension regex (default: .py)"
      echo -e "  -l\t only changed lines (default: 0)"
      echo -e "  -h\t show this help message and exit"
      exit 0
      ;;
    \?)
      echo -e "Invalid option: $OPTARG \ngit-diff-lint -h for help" >&2
      exit 1
      ;;
    :)
      echo -e "Option -$OPTARG requires an argument\ngit-diff-lint -h for help" >&2
      exit 1
      ;;
  esac
done

# check lint exist
# https://stackoverflow.com/a/53798785/1203241
function is_bin_in_path {
    builtin type -P "$1" &> /dev/null
}
if ! is_bin_in_path "$LINT" ; then
  echo "$LINT: not found, have you install it?"
  exit $?
fi

DIFF=$(git diff --name-only --diff-filter=d $(git merge-base HEAD $BRANCH) | grep "${EXT}$")

if [ -n "$DIFF" ]
then
  OUT=0

  # in golint, we can't lint two files in different packages
  # i.e. we can't do `golint main.go pkg/handler.go`
  # so we changed to lint files one by one
  ERRORS=""
  while read -r file; do
    ERRORS+=$(eval $LINT $file 2>&1)
    if [ $? ]; then
      OUT=1
      ERRORS+="\n"
    fi
  done <<< "$DIFF"

  if [[ $LINES -eq 1 ]]; then # lint changed file's added line
    OUT=0
    DIFF_LINE=$(git --no-pager diff $(git merge-base HEAD $BRANCH) -U0 | diff-lines)
    while read -r line; do
      if [ -z "$line" ]; then
        continue
      fi
      echo -e "$ERRORS" | grep "$line" >&2
      if [[ $? -eq "0" ]]; then
        OUT=1
      fi
    done <<< "$DIFF_LINE"
  elif [ $OUT ]; then # lint all changed file
    echo -e "$ERRORS" >&2
  fi

  exit $OUT
else
  exit 0
fi

